
---
apiVersion: v1
kind: Config
current-context: shoot--kyma--c-4dbaad3
clusters:
- name: shoot--kyma--c-4dbaad3
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1akNDQWM2Z0F3SUJBZ0lRUGN3NitJMjlpMEVPdUFLR2FQL0NLREFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TWpFeE1URXdOelF4TVRWYUZ3MHpNakV4TVRFd056UXhNVFZhTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFwMUtxCi9YNStQM2JHKzNBY00xdmZZcElQZG1hQ0w4cHhMK2lGcEprYUw2UXBpb1NDSHJCcXNld1BXd3NTbjl5NmxCQTMKY0NOc2JxcG12VmcxL1FEMkV5Q2owWlBRZURGR2E3TVVJdm0rU0Jna3VOV1l1b2NPQWt5bENMWUlqUDlwQXhuQQpobC9pem9SeVRSdnBWVDhocFZtd1JKOXpJRko3SHk3VGpGam5pMEM3OUVCWmp0WHZWNFd1SWo3SEpXOHIxeHJ6Cnk1TEdLd1V6bms4a25KbnJtdEdsR0cwbmpOSUVrWDRVdXZiTUtIWTlVYTBmSGVCcDlNMUVLUEJpSmpxRzBhZjkKNFJNYVRVOG82K0F3ekp0ZWRlUHNsMVdvNjR3b2VLTVVFWGkyUHA4NmdPdENpRC9udTJ4ZmU1K0dCMG5vMFdGQwpJYUFhNlFnb2FLRVdDR05QandJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBYVl3RHdZRFZSMFRBUUgvCkJBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUdzby9uTlJBZm5iZU01R1dPTEw0czB4SHMzOHdEUVlKS29aSWh2Y04KQVFFTEJRQURnZ0VCQUVxQXRla2tnYkpuSEI5UllrbGlEU3UwKzV2MmorenJYYXlGQ0RBOUF4MkNDV1BlKzRHQwpKa2JPYzNSMER6TnNxaEgzZDVkbmpONnBxaVNEVzVob3pFbm5BdURsVVE0aUEwSzM4UENISEs5a01oV28zWXE5CmZzajF5enZzUmJ5RENvR1QxZzZnQnNLWTdMckVyQk1WdHZDdE1KMFMzWU94YUkrRUVmSzN5S01FYTBsZmFoV2oKd3hBbDYxU1NVN1F3UGdCY1NoY0x5UXdKV0x6UnhqSk05TjlVZnlPcVhGWS93cDRkY1pxUGEyT3BpTmttQmVyRgphTy9VZWRYcDlGNFIvaWFqdFRicEI0VnpkUHpwbWU5RHdaTkNMMzYwSU90cEh4a0xxMWFucjhNZzNsOVd2Qk9NClpQTXphcE9yMVdrdkt1OFAxdjJybzJZUWJpQmF6cGl3MGswPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.c-4dbaad3.kyma.ondemand.com
contexts:
- name: shoot--kyma--c-4dbaad3
  context:
    cluster: shoot--kyma--c-4dbaad3
    user: shoot--kyma--c-4dbaad3
users:
- name: shoot--kyma--c-4dbaad3
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--oidc-issuer-url=https://kyma.accounts.ondemand.com"
      - "--oidc-client-id=12b13a26-d993-4d0c-aa08-5f5852bbdff6"
      - "--oidc-extra-scope=email"
      - "--oidc-extra-scope=openid"
      command: kubectl-oidc_login
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
