name: Build and publish Docker image

on:
  push:
    branches: [ main ]

env:
  HUB: ghcr.io
  TAG: latest


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: |
          docker build -t ${HUB}/kyma:${TAG} .

      
    - name: Push the image to GitHub Package Registry
      if: ${{ success() }}
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ${HUB} --username ${USER} --password-stdin
        docker push docker push ${HUB}/${GITHUB_REPOSITORY}:${TAG}
