name: Build and publish Docker image

on:
  push:
    branches: [ main ]

env:
  HUB: ghcr.io
  TAG: latest


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: |
          docker build . --tag ghcr.io/deselikem/kyma-dev-demo:latest
          
    - name: Push the image to GitHub Package Registry
      if: ${{ success() }}
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ${HUB} --username ${USER} --password-stdin
        docker run ghcr.io/deselikem/kyma-dev-demo-demo:latest
        docker push ghcr.io/deselikem/kyma-dev-demo-demo:latest
